/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RSVPStatus = IDL.Variant({
  'maybe' : IDL.Null,
  'notAttending' : IDL.Null,
  'attending' : IDL.Null,
});
export const RSVP = IDL.Record({
  'status' : RSVPStatus,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
});
export const WeddingDetails = IDL.Record({
  'weddingDate' : IDL.Text,
  'venueAddress' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'coupleNames' : IDL.Text,
  'venueName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getRSVPByEmail' : IDL.Func([IDL.Text], [RSVP], ['query']),
  'getWeddingDetails' : IDL.Func([], [WeddingDetails], ['query']),
  'setWeddingDetails' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'submitRSVP' : IDL.Func(
      [IDL.Text, IDL.Text, RSVPStatus, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RSVPStatus = IDL.Variant({
    'maybe' : IDL.Null,
    'notAttending' : IDL.Null,
    'attending' : IDL.Null,
  });
  const RSVP = IDL.Record({
    'status' : RSVPStatus,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
  });
  const WeddingDetails = IDL.Record({
    'weddingDate' : IDL.Text,
    'venueAddress' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'coupleNames' : IDL.Text,
    'venueName' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getRSVPByEmail' : IDL.Func([IDL.Text], [RSVP], ['query']),
    'getWeddingDetails' : IDL.Func([], [WeddingDetails], ['query']),
    'setWeddingDetails' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'submitRSVP' : IDL.Func(
        [IDL.Text, IDL.Text, RSVPStatus, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };