/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WeddingDetails {
    weddingDate: string;
    venueAddress: string;
    note?: string;
    coupleNames: string;
    venueName: string;
}
export interface RSVP {
    status: RSVPStatus;
    name: string;
    email: string;
    message?: string;
}
export enum RSVPStatus {
    maybe = "maybe",
    notAttending = "notAttending",
    attending = "attending"
}
export interface backendInterface {
    getAllRSVPs(): Promise<Array<RSVP>>;
    getRSVPByEmail(email: string): Promise<RSVP>;
    getWeddingDetails(): Promise<WeddingDetails>;
    setWeddingDetails(coupleNames: string, weddingDate: string, venueName: string, venueAddress: string, note: string | null): Promise<void>;
    submitRSVP(name: string, email: string, status: RSVPStatus, message: string | null): Promise<void>;
}
import type { RSVP as _RSVP, RSVPStatus as _RSVPStatus, WeddingDetails as _WeddingDetails } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRSVPByEmail(arg0: string): Promise<RSVP> {
        if (this.processError) {
            try {
                const result = await this.actor.getRSVPByEmail(arg0);
                return from_candid_RSVP_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRSVPByEmail(arg0);
            return from_candid_RSVP_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeddingDetails(): Promise<WeddingDetails> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeddingDetails();
                return from_candid_WeddingDetails_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeddingDetails();
            return from_candid_WeddingDetails_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async setWeddingDetails(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setWeddingDetails(arg0, arg1, arg2, arg3, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setWeddingDetails(arg0, arg1, arg2, arg3, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: string, arg2: RSVPStatus, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, to_candid_RSVPStatus_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, to_candid_RSVPStatus_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_RSVPStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RSVPStatus): RSVPStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_RSVP_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RSVP): RSVP {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_WeddingDetails_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeddingDetails): WeddingDetails {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _RSVPStatus;
    name: string;
    email: string;
    message: [] | [string];
}): {
    status: RSVPStatus;
    name: string;
    email: string;
    message?: string;
} {
    return {
        status: from_candid_RSVPStatus_n4(_uploadFile, _downloadFile, value.status),
        name: value.name,
        email: value.email,
        message: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.message))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weddingDate: string;
    venueAddress: string;
    note: [] | [string];
    coupleNames: string;
    venueName: string;
}): {
    weddingDate: string;
    venueAddress: string;
    note?: string;
    coupleNames: string;
    venueName: string;
} {
    return {
        weddingDate: value.weddingDate,
        venueAddress: value.venueAddress,
        note: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.note)),
        coupleNames: value.coupleNames,
        venueName: value.venueName
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maybe: null;
} | {
    notAttending: null;
} | {
    attending: null;
}): RSVPStatus {
    return "maybe" in value ? RSVPStatus.maybe : "notAttending" in value ? RSVPStatus.notAttending : "attending" in value ? RSVPStatus.attending : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RSVP>): Array<RSVP> {
    return value.map((x)=>from_candid_RSVP_n2(_uploadFile, _downloadFile, x));
}
function to_candid_RSVPStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RSVPStatus): _RSVPStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RSVPStatus): {
    maybe: null;
} | {
    notAttending: null;
} | {
    attending: null;
} {
    return value == RSVPStatus.maybe ? {
        maybe: null
    } : value == RSVPStatus.notAttending ? {
        notAttending: null
    } : value == RSVPStatus.attending ? {
        attending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
